export const Users = [
    {
      id:1,
      profilePicture: "person/A1.jpg",
      username: "Tina",
    },
    {
      id:2,
      profilePicture: "person/A2.jpg",
      username: "Amie",
    },
    {
      id:3,
      profilePicture: "person/A3.jpg",
      username: "Sokhou",
    },
    {
      id:4,
      profilePicture: "person/A4.jpg",
      username: "Khady",
    },
    {
      id:5,
      profilePicture: "person/A5.jpg",
      username: "Fatou",
    },
    {
      id:6,
      profilePicture: "person/A6.jpg",
      username: "Hawa",
    },
    {
      id:7,
      profilePicture: "person/A7.jpg",
      username: "Ndeye Amie",
    },
    {
      id:8,
      profilePicture: "person/A8.jpg",
      username: "Hawa",
    },
    {
      id:9,
      profilePicture: "person/A7.jpg",
      username: "Marieme",
    },
    {
      id:10,
      profilePicture: "person/A5.jPg",
      username: "Sibo",
    },
  ];
  
  export const Posts = [
    {
      id: 1,
      desc: "Love For All, Hatred For None.",
      photo: "post/cuisine.jpg",
      date: "5 mins ago",
      userId: 1,
      like: 32,
      comment: 9,
    },
    {
      id: 2,
      photo: "post/image.jpg",
      date: "15 mins ago",
      userId: 2,
      like: 2,
      comment: 1,
    },
    {
      id: 3,
      desc: "Every moment is a fresh beginning.",
      photo: "post/tort.jpg",
      date: "1 hour ago",
      userId: 3,
      like: 61,
      comment: 2,
    },
    {
      id: 4,
      photo: "post/tot.jpg",
      date: "4 hours ago",
      userId: 4,
      like: 7,
      comment: 3,
    },
    {
      id: 5,
      photo: "post/route.jpg",
      date: "5 hours ago",
      userId: 5,
      like: 23,
      comment: 5,
    },
    {
      id: 6,
      photo: "person/A6.jpg",
      date: "1 day ago",
      userId: 6,
      like: 44,
      comment: 6,
    },
    {
      id: 7,
      desc: "Never regret anything that made you smile.",
      photo: "person/A7.jpg",
      date: "2 days ago",
      userId: 7,
      like: 52,
      comment: 3,
    },
    {
      id: 8,
      desc: "Never regret anything that made you smile.",
      photo: "person/A8.jpg",
      date: "3 days ago",
      userId: 8,
      like: 15,
      comment: 1,
    },
    {
      id: 9,
      desc: "Change the world by being yourself.",
      photo: "person/A9.jpg",
      date: "5 days ago",
      userId: 9,
      like: 11,
      comment: 2,
    },
    {
      id: 10,
      desc: "Never regret anything that made you smile.",
      photo: "person/A4.jpg",
      date: "1 week ago",
      userId: 10,
      like: 104,
      comment: 12,
    },
  ];